name: Setup SWI-Prolog
description: Installs the specified SWI-Prolog version
inputs:
  swi-prolog-branch:
    description: SWI-Prolog branch (stable or devel)
    required: false
    default: devel
  swi-prolog-version:
    description: SWI-Prolog version to install
    required: true
    default: latest
runs:
  using: 'node12'
  main: 'src/setup-swi-prolog.js'
branding:
  icon: 'box'
  color: 'blue'
